# Generated by Django 3.2 on 2025-08-20 03:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vinculaciones', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('historial', '0001_initial'),
        ('empresa', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workhistory',
            name='changed_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workhistory',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.company'),
        ),
        migrations.AddField(
            model_name='workhistory',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workhistory_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workhistory',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_workhistory_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workhistory',
            name='employment_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vinculaciones.employmentlink'),
        ),
        migrations.AddField(
            model_name='workhistory',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_workhistory_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
