# Generated by Django 5.1.6 on 2025-04-16 00:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('historial', '0002_initial'),
        ('vinculaciones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workhistory',
            name='employment_link',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vinculaciones.employmentlink'),
        ),
    ]
