# Generated by Django 5.1.6 on 2025-04-29 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam_type', models.CharField(choices=[('Ingreso', 'Ingreso'), ('Periódico', 'Periódico'), ('Retiro', 'Retiro')], max_length=20)),
                ('date', models.DateField()),
                ('entity', models.CharField(max_length=100)),
                ('aptitude', models.CharField(max_length=100)),
                ('recommendations', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='medical-exams/')),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
