# Generated by Django 3.2 on 2025-08-20 03:36

import apps.salud_ocupacional.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.TimeField(blank=True, null=True)),
                ('reason', models.CharField(help_text='Motivo de la cita (examen de ingreso, control, retiro, etc.)', max_length=200)),
                ('status', models.CharField(choices=[('scheduled', 'Agendada'), ('completed', 'Completada'), ('canceled', 'Cancelada'), ('no_show', 'No asistió')], default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True, help_text='Observaciones adicionales')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'medical_appointments',
                'ordering': ['-date', '-time'],
            },
        ),
        migrations.CreateModel(
            name='MedicalExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exam_type', models.CharField(choices=[('Médico general', 'Médico general'), ('Médico ocupacional', 'Médico ocupacional'), ('Ingreso osteomuscular con énfasis en altura', 'Ingreso osteomuscular con énfasis en altura'), ('Laboratorio', 'Laboratorio'), ('Visión', 'Visión'), ('Auditivo', 'Auditivo'), ('Espirometría', 'Espirometría'), ('Electrocardiograma', 'Electrocardiograma'), ('Radio de tórax', 'Radio de tórax'), ('Psicológico', 'Psicológico'), ('Psicotécnico', 'Psicotécnico'), ('Osteomuscular', 'Osteomuscular'), ('Pruebas de embarazo', 'Pruebas de embarazo'), ('Específicas', 'Específicas')], max_length=100)),
                ('exam_phase', models.CharField(choices=[('Ingreso', 'Ingreso'), ('Periódico', 'Periódico'), ('Retiro', 'Retiro')], max_length=20)),
                ('date', models.DateField()),
                ('entity_ips', models.CharField(max_length=100)),
                ('aptitude', models.CharField(max_length=100)),
                ('recommendations', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=apps.salud_ocupacional.models.document_upload_path)),
                ('next_due_months', models.IntegerField(blank=True, choices=[(3, '3 meses'), (6, '6 meses'), (9, '9 meses'), (12, '12 meses'), (15, '15 meses'), (18, '18 meses'), (21, '21 meses'), (24, '24 meses')], null=True)),
                ('metrics', models.JSONField(blank=True, help_text="Resultados específicos (p.ej. {'dB':25,'next_due':'2025-10-01'})", null=True)),
                ('next_due', models.DateField(blank=True, help_text='Fecha calculada para próximo examen', null=True)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exams', to='salud_ocupacional.medicalappointment')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.company')),
            ],
            options={
                'verbose_name': 'Examen Médico',
                'verbose_name_plural': 'Exámenes Médicos',
                'db_table': 'medical_exams',
                'ordering': ['-date'],
            },
        ),
    ]
