# Generated by Django 5.1.6 on 2025-04-23 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0004_alter_employeedocument_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exam_type', models.CharField(choices=[('Ingreso', 'Ingreso'), ('Periódico', 'Periódico'), ('Retiro', 'Retiro')], max_length=20)),
                ('date', models.DateField()),
                ('entity', models.CharField(max_length=100)),
                ('aptitude', models.CharField(max_length=100)),
                ('recommendations', models.TextField(blank=True, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='medical-exams/')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.employee')),
            ],
        ),
    ]
