# Generated by Django 3.2 on 2025-08-20 03:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('empresa', '0002_initial'),
        ('salud_ocupacional', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalexam',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_medicalexam_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicalexam',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_medicalexam_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicalexam',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.employee'),
        ),
        migrations.AddField(
            model_name='medicalexam',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_medicalexam_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicalappointment',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_appointments', to='empresa.company'),
        ),
        migrations.AddField(
            model_name='medicalappointment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medical_appointments', to='empleados.employee'),
        ),
    ]
