# Generated by Django 3.2 on 2025-06-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salud_ocupacional", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="medicalexam",
            old_name="entity",
            new_name="entity_ips",
        ),
        migrations.RemoveField(
            model_name="medicalexam",
            name="risk_level",
        ),
        migrations.RemoveField(
            model_name="medicalexam",
            name="sub_type",
        ),
        migrations.AddField(
            model_name="medicalexam",
            name="next_due_months",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (3, "3 meses"),
                    (6, "6 meses"),
                    (9, "9 meses"),
                    (12, "12 meses"),
                    (15, "15 meses"),
                    (18, "18 meses"),
                    (21, "21 meses"),
                    (24, "24 meses"),
                ],
                null=True,
            ),
        ),
    ]
