# Generated by Django 5.1.6 on 2025-05-01 21:22

import apps.salud_ocupacional.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salud_ocupacional", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="medicalexam",
            options={
                "ordering": ["-date"],
                "verbose_name": "Examen Médico",
                "verbose_name_plural": "Exámenes Médicos",
            },
        ),
        migrations.RenameField(
            model_name="medicalexam",
            old_name="exam_type",
            new_name="exam_phase",
        ),
        migrations.AddField(
            model_name="medicalexam",
            name="metrics",
            field=models.JSONField(
                blank=True,
                help_text="Resultados específicos (p.ej. {'dB':25,'next_due':'2025-10-01'})",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="medicalexam",
            name="next_due",
            field=models.DateField(
                blank=True, help_text="Fecha calculada para próximo examen", null=True
            ),
        ),
        migrations.AddField(
            model_name="medicalexam",
            name="risk_level",
            field=models.CharField(
                choices=[
                    ("I", "Bajo"),
                    ("II", "Medio"),
                    ("III", "Alto"),
                    ("IV", "Crítico"),
                ],
                default="II",
                help_text="Nivel de riesgo SST del puesto",
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name="medicalexam",
            name="sub_type",
            field=models.CharField(
                choices=[
                    ("Audiometría", "Audiometría"),
                    ("Espirometría", "Espirometría"),
                    ("Visión", "Visión"),
                    ("Laboratorio", "Laboratorio"),
                    ("Presión arterial", "Presión arterial"),
                    ("Otro", "Otro"),
                ],
                default="Otro",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="medicalexam",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to=apps.salud_ocupacional.models.document_upload_path,
            ),
        ),
    ]
