# Generated by Django 3.2 on 2025-06-12 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("salud_ocupacional", "0003_auto_20250612_1029"),
    ]

    operations = [
        migrations.AddField(
            model_name="medicalexam",
            name="exam_type",
            field=models.CharField(
                choices=[
                    ("Médico general", "Médico general"),
                    ("Médico ocupacional", "Médico ocupacional"),
                    (
                        "Ingreso osteomuscular con énfasis en altura",
                        "Ingreso osteomuscular con énfasis en altura",
                    ),
                    ("Laboratorio", "Laboratorio"),
                    ("Visión", "Visión"),
                    ("Auditivo", "Auditivo"),
                    ("Espirometría", "Espirometría"),
                    ("Electrocardiograma", "Electrocardiograma"),
                    ("Radio de tórax", "Radio de tórax"),
                    ("Psicológico", "Psicológico"),
                    ("Psicotécnico", "Psicotécnico"),
                    ("Osteomuscular", "Osteomuscular"),
                    ("Pruebas de embarazo", "Pruebas de embarazo"),
                    ("Específicas", "Específicas"),
                ],
                default=1,
                max_length=100,
            ),
            preserve_default=False,
        ),
    ]
