# Generated by Django 5.1.6 on 2025-04-24 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reintegro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(help_text='Fecha inicio del proceso de reintegro')),
                ('end_date', models.DateField(blank=True, help_text='Fecha de finalización (si aplica)', null=True)),
                ('medical_recommendations', models.TextField(blank=True, help_text='Recomendaciones médicas para el reintegro')),
                ('position_modification', models.BooleanField(default=False, help_text='¿Hubo modificación de cargo?')),
                ('workplace_adaptation', models.BooleanField(default=False, help_text='¿Hubo adaptación en el puesto de trabajo?')),
                ('observations', models.TextField(blank=True)),
                ('successful', models.BooleanField(default=False, help_text='¿Reintegro exitoso?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.employee')),
            ],
        ),
    ]
