# Generated by Django 5.1.6 on 2025-04-23 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0004_alter_employeedocument_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkAccident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('injury_type', models.CharField(max_length=100)),
                ('severity', models.CharField(choices=[('Leve', 'Leve'), ('Grave', 'Grave'), ('Mortal', 'Mortal')], max_length=30)),
                ('reported_to_arl', models.BooleanField(default=False)),
                ('days_lost', models.IntegerField(default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.employee')),
            ],
        ),
    ]
