# Generated by Django 5.1.6 on 2025-04-24 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkAccident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_type', models.CharField(choices=[('Accidente', 'Accidente de Trabajo'), ('Incidente', 'Incidente')], default='Accidente', max_length=20)),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('injury_type', models.CharField(blank=True, max_length=100)),
                ('severity', models.CharField(blank=True, choices=[('Leve', 'Leve'), ('Grave', 'Grave'), ('Mortal', 'Mortal')], default='Leve', max_length=30)),
                ('reported_to_arl', models.BooleanField(default=False)),
                ('days_lost', models.IntegerField(blank=True, default=0, null=True)),
                ('training_valid', models.BooleanField(default=False, help_text='¿Tenía capacitación vigente?')),
                ('medical_exam_valid', models.BooleanField(default=False, help_text='¿Tenía aptitud médica vigente?')),
                ('corrective_actions', models.TextField(blank=True)),
                ('evidence_file', models.FileField(blank=True, null=True, upload_to='accident_evidence/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.employee')),
            ],
        ),
        migrations.CreateModel(
            name='WorkAtHeightPermit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=150)),
                ('work_description', models.TextField()),
                ('checklist', models.JSONField(blank=True, default=dict, help_text='Checklist de control de riesgos')),
                ('approved', models.BooleanField(default=False)),
                ('supervisor', models.CharField(blank=True, max_length=100)),
                ('evidence_file', models.FileField(blank=True, null=True, upload_to='height_permits/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.employee')),
            ],
        ),
    ]
