# Generated by Django 3.2 on 2025-07-02 00:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0002_initial'),
        ('seguridad_industrial', '0001_initial'),
        ('empleados', '0003_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workatheightpermit',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workatheightpermit_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workatheightpermit',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_workatheightpermit_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workatheightpermit',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.employee'),
        ),
        migrations.AddField(
            model_name='workatheightpermit',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_workatheightpermit_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workaccident',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.company'),
        ),
        migrations.AddField(
            model_name='workaccident',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_workaccident_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workaccident',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_workaccident_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='workaccident',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.employee'),
        ),
        migrations.AddField(
            model_name='workaccident',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_workaccident_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='workaccident',
            index=models.Index(fields=['employee', 'incident_type'], name='seguridad_i_employe_e8c660_idx'),
        ),
        migrations.AddIndex(
            model_name='workaccident',
            index=models.Index(fields=['is_deleted'], name='seguridad_i_is_dele_0b3fce_idx'),
        ),
    ]
