# Generated by Django 5.1.6 on 2025-04-29 05:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empleados", "0002_initial"),
        ("seguridad_industrial", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="workaccident",
            name="date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="workaccident",
            name="incident_type",
            field=models.CharField(
                choices=[
                    ("Accidente", "Accidente de Trabajo"),
                    ("Incidente", "Incidente"),
                ],
                db_index=True,
                default="Accidente",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="workaccident",
            name="severity",
            field=models.CharField(
                choices=[("Leve", "Leve"), ("Grave", "Grave"), ("Mortal", "Mortal")],
                db_index=True,
                default="Leve",
                max_length=30,
            ),
        ),
        migrations.AddIndex(
            model_name="workaccident",
            index=models.Index(
                fields=["employee", "incident_type"],
                name="seguridad_i_employe_e8c660_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="workaccident",
            index=models.Index(
                fields=["is_deleted"], name="seguridad_i_is_dele_0b3fce_idx"
            ),
        ),
    ]
