# Generated by Django 3.2 on 2025-07-02 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_initial'),
        ('indicadores', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='indicator',
            unique_together={('name', 'company')},
        ),
    ]
