# Generated by Django 3.2 on 2025-07-02 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contratistas', '0001_initial'),
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractorcontact',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contractorcontact_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contractorcontact',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_contractorcontact_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contractorcontact',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_contractorcontact_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contractorcompany',
            name='company',
            field=models.ForeignKey(help_text='Empresa/tenant al que pertenece este registro', on_delete=django.db.models.deletion.PROTECT, to='empresa.company'),
        ),
        migrations.AddField(
            model_name='contractorcompany',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contractorcompany_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contractorcompany',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_contractorcompany_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contractorcompany',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_contractorcompany_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
