# Generated by Django 5.1.6 on 2025-04-24 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SuggestionBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Sugerencia', 'Sugerencia'), ('Queja', 'Queja'), ('Reporte', 'Reporte de Condición Insegura'), ('Mejora', 'Propuesta de Mejora'), ('Otro', 'Otro')], max_length=30)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('anonymous', models.BooleanField(default=False)),
                ('response', models.TextField(blank=True, help_text='Respuesta de la empresa/SST')),
                ('responded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empleados.employee')),
            ],
        ),
    ]
