# Generated by Django 3.2 on 2025-07-18 03:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('legal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='legalrequirement',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_legalrequirement_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='legalrequirement',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_legalrequirement_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='legalrequirement',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_legalrequirement_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
