# Generated by Django 5.1.6 on 2025-04-24 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stakeholder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('stakeholder_type', models.CharField(choices=[('Cliente', 'Cliente'), ('Proveedor', 'Proveedor'), ('Contratista', 'Contratista'), ('ARL', 'ARL'), ('Aseguradora', 'Aseguradora'), ('Autoridad', 'Autoridad Reguladora'), ('Comunidad', 'Comunidad'), ('Otro', 'Otro')], max_length=30)),
                ('contact_info', models.CharField(blank=True, max_length=250)),
                ('interests', models.TextField(help_text='Expectativas o intereses sobre el SG-SST')),
                ('requirements', models.TextField(blank=True, help_text='Requisitos legales, contractuales, etc.')),
                ('document', models.FileField(blank=True, help_text='Documento asociado', null=True, upload_to='stakeholder_docs/')),
                ('last_contact', models.DateField(blank=True, help_text='Último contacto/actualización', null=True)),
                ('comments', models.TextField(blank=True, help_text='Observaciones internas')),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('work_area', models.ForeignKey(blank=True, help_text='Área/proceso asociado', null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.workarea')),
            ],
        ),
    ]
