# Generated by Django 3.2 on 2025-08-20 03:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stakeholders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogos', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stakeholder',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_stakeholder_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_stakeholder_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_stakeholder_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='stakeholder',
            name='work_area',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.workarea'),
        ),
    ]
