# Generated by Django 5.1.6 on 2025-05-25 21:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empleados", "0002_initial"),
        ("empresa", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="company",
            field=models.ForeignKey(
                blank=True,
                help_text="Empresa a la que pertenece el empleado",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employees",
                to="empresa.company",
            ),
        ),
    ]
