# Generated by Django 5.1.6 on 2025-05-26 00:37

import django_multitenant.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("empleados", "0003_employee_company"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="employee",
            managers=[
                ("objects", django_multitenant.models.TenantManager()),
            ],
        ),
    ]
