# Generated by Django 5.1.6 on 2025-04-21 22:28

import apps.empleados.models  # ✅ nueva ruta de la app

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0003_documenttype_employeedocument'),  # 👈 Esto está bien, porque se refiere al nombre de la app en la base de datos (no al módulo Python)
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedocument',
            name='file',
            field=models.FileField(upload_to=apps.empleados.models.document_upload_path),
        ),
    ]
