# Generated by Django 3.2 on 2025-06-12 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empleados", "0004_alter_employee_managers"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="compensation_fund",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
