# Generated by Django 3.2 on 2025-07-18 03:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentInventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=100, verbose_name='Categoría')),
                ('serial', models.CharField(blank=True, max_length=100, null=True, verbose_name='Serial')),
                ('cantidad', models.PositiveIntegerField(default=1, verbose_name='Cantidad')),
                ('fecha_compra', models.DateField(verbose_name='Fecha de compra')),
                ('certificado', models.FileField(blank=True, null=True, upload_to='equipment_certificates/', verbose_name='Certificado')),
                ('estado', models.CharField(blank=True, max_length=50, verbose_name='Estado')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipment_inventory', to='empresa.company')),
            ],
            options={
                'db_table': 'equipment_inventory',
                'ordering': ['categoria', 'serial'],
            },
        ),
        migrations.CreateModel(
            name='EquipmentInspection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de inspección')),
                ('resultado', models.CharField(max_length=100, verbose_name='Resultado')),
                ('tecnico', models.CharField(max_length=100, verbose_name='Técnico')),
                ('evidencia', models.FileField(blank=True, null=True, upload_to='equipment_inspections/', verbose_name='Evidencia (PDF/imagen)')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspections', to='equipment.equipmentinventory')),
            ],
            options={
                'db_table': 'equipment_inspections',
                'ordering': ['-fecha'],
            },
        ),
    ]
