# Generated by Django 5.1.6 on 2025-05-13 05:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("empresa", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="EquipmentInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "categoria",
                    models.CharField(max_length=100, verbose_name="Categoría"),
                ),
                ("serial", models.CharField(max_length=100, verbose_name="Serial")),
                ("fecha_compra", models.DateField(verbose_name="Fecha de compra")),
                (
                    "certificado",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="equipment_certificates/",
                        verbose_name="Certificado (PDF/imagen)",
                    ),
                ),
                (
                    "estado",
                    models.CharField(blank=True, max_length=50, verbose_name="Estado"),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="equipment_inventory",
                        to="empresa.company",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EquipmentInspection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fecha", models.DateField(verbose_name="Fecha de inspección")),
                (
                    "resultado",
                    models.CharField(max_length=100, verbose_name="Resultado"),
                ),
                ("tecnico", models.CharField(max_length=100, verbose_name="Técnico")),
                (
                    "evidencia",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="equipment_inspections/",
                        verbose_name="Evidencia (PDF/imagen)",
                    ),
                ),
                (
                    "equipment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inspections",
                        to="equipment.equipmentinventory",
                    ),
                ),
            ],
        ),
    ]
