# Generated by Django 5.1.6 on 2025-05-13 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("equipment", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="equipmentinventory",
            name="cantidad",
            field=models.PositiveIntegerField(default=1, verbose_name="Cantidad"),
        ),
        migrations.AlterField(
            model_name="equipmentinventory",
            name="certificado",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="equipment_certificates/",
                verbose_name="Certificado",
            ),
        ),
        migrations.AlterField(
            model_name="equipmentinventory",
            name="serial",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Serial"
            ),
        ),
    ]
