# Generated by Django 5.1.6 on 2025-04-29 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ARO",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                ("description", models.TextField()),
                ("hazard", models.CharField(max_length=150)),
                ("risk", models.CharField(max_length=150)),
                ("control", models.TextField()),
                ("evidence", models.FileField(blank=True, null=True, upload_to="aro/")),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="ATS",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                ("activity", models.CharField(max_length=150)),
                ("hazard", models.CharField(max_length=150)),
                ("risk", models.CharField(max_length=150)),
                ("control", models.TextField()),
                ("evidence", models.FileField(blank=True, null=True, upload_to="ats/")),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="ErgonomicAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("area", models.CharField(blank=True, max_length=100)),
                ("date", models.DateField()),
                ("evaluation_type", models.CharField(blank=True, max_length=100)),
                ("summary", models.TextField(blank=True)),
                (
                    "file",
                    models.FileField(blank=True, null=True, upload_to="ergonomics/"),
                ),
                ("responsible", models.CharField(blank=True, max_length=100)),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
