# Generated by Django 3.2 on 2025-07-10 01:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0002_initial'),
        ('ergonomia', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('catalogos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ergonomicassessment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ergonomicassessment_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ergonomicassessment',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_ergonomicassessment_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ergonomicassessment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ergonomic_assessments', to='empleados.employee'),
        ),
        migrations.AddField(
            model_name='ergonomicassessment',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.position'),
        ),
        migrations.AddField(
            model_name='ergonomicassessment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_ergonomicassessment_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ats',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_ats_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ats',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_ats_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ats',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empleados.employee'),
        ),
        migrations.AddField(
            model_name='ats',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.position'),
        ),
        migrations.AddField(
            model_name='ats',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_ats_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aro',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_aro_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aro',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_aro_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='aro',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empleados.employee'),
        ),
        migrations.AddField(
            model_name='aro',
            name='position',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='catalogos.position'),
        ),
        migrations.AddField(
            model_name='aro',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_aro_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
