# Generated by Django 5.1.6 on 2025-04-28 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acciones_correctivas', '0004_riskaction'),
        ('empleados', '0002_initial'),
        ('riesgos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskassessment',
            name='action_item',
            field=models.ForeignKey(blank=True, help_text='Acción correctiva/preventiva asociada (si aplica)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='acciones_correctivas.actionitem'),
        ),
        migrations.CreateModel(
            name='RiskControl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('implemented', models.BooleanField(default=False)),
                ('due_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empleados.employee')),
                ('risk_assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_controls', to='riesgos.riskassessment')),
            ],
        ),
        migrations.CreateModel(
            name='RiskReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_date', models.DateField()),
                ('comments', models.TextField(blank=True)),
                ('risk_level_after_review', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empleados.employee')),
                ('risk_assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='riesgos.riskassessment')),
            ],
        ),
    ]
