# Generated by Django 3.2 on 2025-08-20 03:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0003_initial'),
        ('riesgos', '0001_initial'),
        ('empresa', '0002_initial'),
        ('acciones_correctivas', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='riskreview',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_riskreview_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='riskreview',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_riskreview_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='riskreview',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empleados.employee'),
        ),
        migrations.AddField(
            model_name='riskreview',
            name='risk_assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='riesgos.riskassessment'),
        ),
        migrations.AddField(
            model_name='riskreview',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_riskreview_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='riskcontrol',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_riskcontrol_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='riskcontrol',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_riskcontrol_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='riskcontrol',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empleados.employee'),
        ),
        migrations.AddField(
            model_name='riskcontrol',
            name='risk_assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='risk_controls', to='riesgos.riskassessment'),
        ),
        migrations.AddField(
            model_name='riskcontrol',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_riskcontrol_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='action_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='acciones_correctivas.actionitem'),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.company'),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_riskassessment_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_riskassessment_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='evaluated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='risk_evaluations', to='empleados.employee'),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='hazard',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riesgos.hazard'),
        ),
        migrations.AddField(
            model_name='riskassessment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_riskassessment_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hazard',
            name='area',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='riesgos.area'),
        ),
        migrations.AddField(
            model_name='hazard',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_hazard_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hazard',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_hazard_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hazard',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_hazard_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controlfollowup',
            name='control',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followups', to='riesgos.riskcontrol'),
        ),
        migrations.AddField(
            model_name='controlfollowup',
            name='performed_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='empleados.employee'),
        ),
        migrations.AddField(
            model_name='controlevidence',
            name='control',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='riesgos.riskcontrol'),
        ),
        migrations.AddField(
            model_name='area',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_area_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='area',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_area_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='area',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='areas_responsible', to='empleados.employee'),
        ),
        migrations.AddField(
            model_name='area',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_area_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='riskassessment',
            index=models.Index(fields=['hazard', 'is_active'], name='risk_assess_hazard__cfa3c3_idx'),
        ),
        migrations.AddIndex(
            model_name='riskassessment',
            index=models.Index(fields=['is_deleted'], name='risk_assess_is_dele_1b0890_idx'),
        ),
    ]
