# Generated by Django 5.1.6 on 2025-04-29 05:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "acciones_correctivas",
            "0003_alter_actionitem_completed_alter_actionitem_due_date_and_more",
        ),
        ("empleados", "0002_initial"),
        ("riesgos", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="riskassessment",
            name="date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="riskassessment",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddIndex(
            model_name="riskassessment",
            index=models.Index(
                fields=["hazard", "is_active"], name="riesgos_ris_hazard__da25ae_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="riskassessment",
            index=models.Index(
                fields=["is_deleted"], name="riesgos_ris_is_dele_51c211_idx"
            ),
        ),
    ]
