# Generated by Django 5.1.6 on 2025-04-21 22:28

import empleados.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0003_documenttype_employeedocument'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedocument',
            name='file',
            field=models.FileField(upload_to=empleados.models.document_upload_path),
        ),
    ]
