# Generated by Django 5.1.6 on 2025-05-11 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("empresa", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SignageInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tipo_senal",
                    models.CharField(max_length=100, verbose_name="Tipo de señal"),
                ),
                (
                    "ubicacion_plano",
                    models.JSONField(verbose_name="Ubicación (geoJSON)"),
                ),
                (
                    "photo",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="signage_inventory/",
                        verbose_name="Evidencia (foto)",
                    ),
                ),
                (
                    "installed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de verificación"
                    ),
                ),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signage_inventory",
                        to="empresa.company",
                    ),
                ),
            ],
        ),
    ]
