# Generated by Django 5.1.6 on 2025-05-12 01:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empleados", "0002_initial"),
        ("safety", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VaccinationRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("vacuna", models.CharField(max_length=100, verbose_name="Vacuna")),
                ("fecha", models.DateField(verbose_name="Fecha de aplicación")),
                (
                    "fecha_vencimiento",
                    models.DateField(verbose_name="Fecha de vencimiento"),
                ),
                (
                    "soporte",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="vaccination_records/",
                        verbose_name="Soporte (PDF/foto)",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vaccinations",
                        to="empleados.employee",
                    ),
                ),
            ],
        ),
    ]
