# Generated by Django 3.2 on 2025-07-02 00:55

from django.db import migrations, models
import django.db.models.deletion
import django_multitenant.mixins
import django_multitenant.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EPPAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_at', models.DateField(auto_now_add=True)),
                ('returned_at', models.DateField(blank=True, null=True)),
                ('condition_on_return', models.TextField(blank=True)),
                ('assigned_by', models.CharField(blank=True, max_length=100)),
                ('evidence', models.FileField(blank=True, null=True, upload_to='epp_evidence/')),
                ('is_active', models.BooleanField(default=True)),
                ('return_reason', models.CharField(blank=True, choices=[('Desgaste', 'Desgaste'), ('Daño', 'Daño'), ('Vencimiento', 'Vencimiento'), ('Pérdida', 'Pérdida'), ('Reposición programada', 'Reposición programada')], max_length=30)),
                ('confirmed', models.BooleanField(default=False)),
                ('confirmation_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='EPPItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('stock', models.IntegerField(default=0)),
                ('expiration_date', models.DateField(blank=True, null=True)),
                ('company', models.ForeignKey(help_text='Empresa/tenant al que pertenece este registro', on_delete=django.db.models.deletion.PROTECT, to='empresa.company')),
            ],
            options={
                'ordering': ['name'],
            },
            bases=(django_multitenant.mixins.TenantModelMixin, models.Model),
            managers=[
                ('objects', django_multitenant.models.TenantManager()),
            ],
        ),
    ]
