# Generated by Django 5.1.6 on 2025-04-26 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('epp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eppassignment',
            name='confirmation_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eppassignment',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eppassignment',
            name='return_reason',
            field=models.CharField(blank=True, choices=[('Desgaste', 'Desgaste'), ('Daño', 'Daño'), ('Vencimiento', 'Vencimiento'), ('Pérdida', 'Pérdida'), ('Reposición programada', 'Reposición programada')], max_length=30),
        ),
    ]
