# Generated by Django 5.1.6 on 2025-04-23 00:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0004_alter_employeedocument_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(max_length=100)),
                ('expiration_date', models.DateField()),
                ('notified', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.employee')),
            ],
        ),
    ]
