# Generated by Django 5.1.6 on 2025-04-29 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DocumentAlert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("alert_type", models.CharField(max_length=100)),
                ("expiration_date", models.DateField()),
                ("notified", models.BooleanField(default=False)),
                ("active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["expiration_date"],
            },
        ),
    ]
