# Generated by Django 3.2 on 2025-07-02 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('empleados', '0003_initial'),
        ('inspecciones', '0001_initial'),
        ('empresa', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inspectiontemplate',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_inspectiontemplate_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspectiontemplate',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_inspectiontemplate_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspectiontemplate',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_inspectiontemplate_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspectionresponse',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_inspectionresponse_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspectionresponse',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_inspectionresponse_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspectionresponse',
            name='inspection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='inspecciones.inspection'),
        ),
        migrations.AddField(
            model_name='inspectionresponse',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inspecciones.inspectionitem'),
        ),
        migrations.AddField(
            model_name='inspectionresponse',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_inspectionresponse_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspectionitem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_inspectionitem_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspectionitem',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_inspectionitem_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspectionitem',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='inspecciones.inspectiontemplate'),
        ),
        migrations.AddField(
            model_name='inspectionitem',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_inspectionitem_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspection',
            name='company',
            field=models.ForeignKey(help_text='Empresa/tenant al que pertenece este registro', on_delete=django.db.models.deletion.PROTECT, to='empresa.company'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_inspection_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspection',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_inspection_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inspection',
            name='performed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inspections_performed', to='empleados.employee'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inspecciones.inspectiontemplate'),
        ),
        migrations.AddField(
            model_name='inspection',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_inspection_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['company_id', 'id'], name='inspections_company_d9d22b_idx'),
        ),
        migrations.AddIndex(
            model_name='inspection',
            index=models.Index(fields=['date'], name='inspections_date_d7cd63_idx'),
        ),
    ]
