# Generated by Django 3.2 on 2025-08-20 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('certificate_file', models.FileField(upload_to='certifications/')),
                ('issued_date', models.DateField(auto_now_add=True)),
                ('expiration_date', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'certifications',
                'ordering': ['-issued_date'],
            },
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('duration_hours', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('modality', models.CharField(blank=True, max_length=20)),
                ('topic', models.CharField(max_length=150)),
                ('date', models.DateField()),
                ('instructor', models.CharField(max_length=100)),
                ('supporting_document', models.FileField(blank=True, null=True, upload_to='training-sessions/')),
            ],
            options={
                'db_table': 'training_sessions',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='TrainingSessionAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('signature_file', models.FileField(blank=True, null=True, upload_to='attendances/')),
                ('attended', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'training_session_attendance',
                'ordering': ['-created_at'],
            },
        ),
    ]
