# Generated by Django 3.2 on 2025-05-27 04:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("empresa", "0005_auto_20250526_2228"),
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="userrole",
            name="company",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="roles",
                to="empresa.company",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="userrole",
            name="name",
            field=models.CharField(max_length=50),
        ),
    ]
