# Generated by Django 5.1.6 on 2025-04-29 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userrole",
            name="is_active",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddIndex(
            model_name="userrole",
            index=models.Index(
                fields=["is_deleted"], name="user_roles_is_dele_0717ce_idx"
            ),
        ),
    ]
