# Generated by Django 3.2 on 2025-05-30 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("usuarios", "0002_auto_20250526_2339"),
    ]

    operations = [
        migrations.AddField(
            model_name="userrole",
            name="access_level",
            field=models.IntegerField(default=1),
        ),
    ]
