# Generated by Django 3.2 on 2025-07-11 00:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cambios', '0001_initial'),
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='changerequest',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_changerequest_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_changerequest_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='requested_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='changerequest',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_changerequest_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='changeimplementation',
            name='change_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='implementation', to='cambios.changerequest'),
        ),
        migrations.AddField(
            model_name='changeimplementation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_changeimplementation_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='changeimplementation',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_changeimplementation_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='changeimplementation',
            name='implemented_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empleados.employee'),
        ),
        migrations.AddField(
            model_name='changeimplementation',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_changeimplementation_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='changeimplementation',
            name='verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='change_verifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='changeevaluation',
            name='change_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='evaluation', to='cambios.changerequest'),
        ),
        migrations.AddField(
            model_name='changeevaluation',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_changeevaluation_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='changeevaluation',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_changeevaluation_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='changeevaluation',
            name='evaluated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='changeevaluation',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_changeevaluation_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='changerequest',
            index=models.Index(fields=['status'], name='cambios_cha_status_3c7d88_idx'),
        ),
        migrations.AddIndex(
            model_name='changerequest',
            index=models.Index(fields=['is_deleted'], name='cambios_cha_is_dele_f6dbdc_idx'),
        ),
    ]
