# Generated by Django 5.1.6 on 2025-04-29 05:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cambios", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="changerequest",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="changerequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pendiente"),
                    ("approved", "Aprobado"),
                    ("rejected", "Rechazado"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="changerequest",
            index=models.Index(fields=["status"], name="cambios_cha_status_3c7d88_idx"),
        ),
        migrations.AddIndex(
            model_name="changerequest",
            index=models.Index(
                fields=["is_deleted"], name="cambios_cha_is_dele_f6dbdc_idx"
            ),
        ),
    ]
