# Generated by Django 5.1.6 on 2025-04-24 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyBrigadeMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('Jefe', 'Jefe de Brigada'), ('PrimerosAuxilios', 'Primeros Auxilios'), ('Evacuacion', 'Evacuación'), ('Incendios', 'Control de Incendios'), ('Comunicaciones', 'Comunicaciones'), ('Otro', 'Otro')], max_length=50)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyDrill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drill_type', models.CharField(choices=[('Evacuacion', 'Evacuación'), ('Incendio', 'Incendio'), ('Sismo', 'Sismo'), ('PrimerosAuxilios', 'Primeros Auxilios'), ('Otro', 'Otro')], max_length=50)),
                ('date', models.DateField()),
                ('objectives', models.TextField()),
                ('findings', models.TextField(blank=True)),
                ('improvement_actions', models.TextField(blank=True)),
                ('evidence_file', models.FileField(blank=True, null=True, upload_to='emergency_drills/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyEquipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Extintor', 'Extintor'), ('Botiquin', 'Botiquín de primeros auxilios'), ('Alarma', 'Alarma'), ('Camilla', 'Camilla'), ('Otro', 'Otro')], max_length=50)),
                ('location', models.CharField(max_length=100)),
                ('inspection_date', models.DateField(blank=True, null=True)),
                ('next_inspection', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
            ],
        ),
    ]
