# Generated by Django 3.2 on 2025-07-11 00:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emergencies', '0001_initial'),
        ('empleados', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyequipment',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_emergencyequipment_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emergencyequipment',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_emergencyequipment_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emergencyequipment',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_emergencyequipment_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emergencydrill',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_emergencydrill_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emergencydrill',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_emergencydrill_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emergencydrill',
            name='participants',
            field=models.ManyToManyField(related_name='drill_participations', to='empleados.Employee'),
        ),
        migrations.AddField(
            model_name='emergencydrill',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_emergencydrill_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emergencybrigademember',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_emergencybrigademember_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emergencybrigademember',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_emergencybrigademember_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='emergencybrigademember',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.employee'),
        ),
        migrations.AddField(
            model_name='emergencybrigademember',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_emergencybrigademember_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
