# Generated by Django 3.2 on 2025-07-10 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('absence_type', models.CharField(choices=[('Incapacidad', 'Incapacidad'), ('Licencia', 'Licencia'), ('Vacaciones', 'Vacaciones')], max_length=30)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('diagnosis_code', models.CharField(blank=True, max_length=20, null=True)),
                ('diagnosis_description', models.CharField(blank=True, max_length=255, null=True)),
                ('health_provider', models.CharField(blank=True, max_length=100, null=True)),
                ('reintegrated', models.BooleanField(default=False)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.company')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
