# Generated by Django 5.1.6 on 2025-04-24 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Absence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absence_type', models.CharField(choices=[('Incapacidad', 'Incapacidad'), ('Licencia', 'Licencia'), ('Vacaciones', 'Vacaciones')], max_length=30)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('diagnosis_code', models.CharField(blank=True, max_length=20, null=True)),
                ('diagnosis_description', models.CharField(blank=True, max_length=255, null=True)),
                ('health_provider', models.CharField(blank=True, max_length=100, null=True)),
                ('reintegrated', models.BooleanField(default=False)),
            ],
        ),
    ]
