# Generated by Django 5.1.6 on 2025-05-11 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("ausentismo", "0001_initial"),
        ("empresa", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="absence",
            name="company",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="empresa.company"
            ),
        ),
    ]
