# Generated by Django 3.2 on 2025-07-02 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('empleados', '0002_employeedocument_company'),
        ('ausentismo', '0002_absence_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='absence',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_absence_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='absence',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_absence_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='absence',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.employee'),
        ),
        migrations.AddField(
            model_name='absence',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_absence_set', to=settings.AUTH_USER_MODEL),
        ),
    ]
