# Generated by Django 3.2 on 2025-07-18 03:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('riesgos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('empleados', '0002_employeedocument_company'),
        ('empresa', '0001_initial'),
        ('acciones_correctivas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='riskaction',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_riskaction_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='riskaction',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_riskaction_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='riskaction',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empleados.employee'),
        ),
        migrations.AddField(
            model_name='riskaction',
            name='risk_assessment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='riesgos.riskassessment'),
        ),
        migrations.AddField(
            model_name='riskaction',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_riskaction_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='improvementplan',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empresa.company'),
        ),
        migrations.AddField(
            model_name='improvementplan',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_improvementplan_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='improvementplan',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_improvementplan_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='improvementplan',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_improvementplan_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actionitem',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_actionitem_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actionitem',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_actionitem_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='actionitem',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='acciones_correctivas.improvementplan'),
        ),
        migrations.AddField(
            model_name='actionitem',
            name='responsible',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empleados.employee'),
        ),
        migrations.AddField(
            model_name='actionitem',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_actionitem_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='actionitem',
            index=models.Index(fields=['plan', 'completed'], name='action_item_plan_id_92d7b8_idx'),
        ),
        migrations.AddIndex(
            model_name='actionitem',
            index=models.Index(fields=['is_deleted'], name='action_item_is_dele_c1aa7b_idx'),
        ),
    ]
