# Generated by Django 5.1.6 on 2025-04-29 05:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("acciones_correctivas", "0002_initial"),
        ("empleados", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="actionitem",
            name="completed",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="actionitem",
            name="due_date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="actionitem",
            name="plan",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="acciones_correctivas.improvementplan",
            ),
        ),
        migrations.AddIndex(
            model_name="actionitem",
            index=models.Index(
                fields=["plan", "completed"], name="acciones_co_plan_id_2f01b3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="actionitem",
            index=models.Index(
                fields=["is_deleted"], name="acciones_co_is_dele_2e7e2d_idx"
            ),
        ),
    ]
