# Generated by Django 5.1.6 on 2025-04-28 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acciones_correctivas', '0003_initial'),
        ('empleados', '0002_initial'),
        ('riesgos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RiskAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('due_date', models.DateField()),
                ('completed', models.BooleanField(default=False)),
                ('evidence', models.FileField(blank=True, null=True, upload_to='risk_actions_evidence/')),
                ('comments', models.TextField(blank=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('responsible', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empleados.employee')),
                ('risk_assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='riesgos.riskassessment')),
            ],
        ),
    ]
