# Generated by Django 3.2 on 2025-06-03 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalogos", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="position",
            name="risk_level",
            field=models.CharField(
                choices=[("bajo", "Bajo"), ("medio", "Medio"), ("alto", "Alto")],
                default=1,
                max_length=10,
            ),
            preserve_default=False,
        ),
    ]
