# Generated by Django 3.2 on 2025-07-02 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_initial'),
        ('catalogos', '0003_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='branch',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='position',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='workarea',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='branch',
            unique_together={('name', 'company')},
        ),
        migrations.AlterUniqueTogether(
            name='position',
            unique_together={('name', 'company')},
        ),
        migrations.AlterUniqueTogether(
            name='workarea',
            unique_together={('name', 'company')},
        ),
    ]
