# Generated by Django 3.2 on 2025-07-18 03:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0003_initial'),
        ('sst_policies', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sstpolicy',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_sstpolicy_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sstpolicy',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_sstpolicy_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sstpolicy',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_sstpolicy_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='policyacceptance',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_policyacceptance_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='policyacceptance',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_policyacceptance_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='policyacceptance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.employee'),
        ),
        migrations.AddField(
            model_name='policyacceptance',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sst_policies.sstpolicy'),
        ),
        migrations.AddField(
            model_name='policyacceptance',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_policyacceptance_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='policyacceptance',
            unique_together={('employee', 'policy')},
        ),
    ]
