# Generated by Django 5.1.6 on 2025-05-06 02:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empleados", "0002_initial"),
        ("vinculaciones", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employmentlink",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="employment_links",
                to="empleados.employee",
            ),
        ),
    ]
