# Generated by Django 5.1.6 on 2025-04-29 05:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empleados", "0002_initial"),
        ("empresa", "0002_initial"),
        ("vinculaciones", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="employmentlink",
            name="start_date",
            field=models.DateField(db_index=True),
        ),
        migrations.AlterField(
            model_name="employmentlink",
            name="status",
            field=models.CharField(
                choices=[
                    ("ACTIVE", "Activo"),
                    ("INACTIVE", "Inactivo"),
                    ("ENDED", "Finalizado"),
                ],
                db_index=True,
                default="ACTIVE",
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name="employmentlink",
            index=models.Index(
                fields=["company", "status"], name="employment__company_7597df_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employmentlink",
            index=models.Index(
                fields=["is_deleted"], name="employment__is_dele_d07563_idx"
            ),
        ),
    ]
