# Generated by Django 5.1.6 on 2025-04-26 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contratistas', '0001_initial'),
        ('empleados', '0002_initial'),
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_type', models.CharField(choices=[('Laboral', 'Laboral'), ('Servicios', 'Servicios'), ('Aprendizaje', 'Aprendizaje'), ('Temporal', 'Temporal'), ('Otro', 'Otro')], max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('renewal_count', models.IntegerField(default=0)),
                ('contract_file', models.FileField(blank=True, null=True, upload_to='contracts/')),
                ('status', models.CharField(choices=[('VIGENTE', 'Vigente'), ('TERMINADO', 'Terminado'), ('LIQUIDADO', 'Liquidado'), ('SUSPENDIDO', 'Suspendido')], default='VIGENTE', max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='empresa.company')),
                ('contractor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contratistas.contractorcompany')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='empleados.employee')),
            ],
        ),
    ]
