# Generated by Django 5.1.6 on 2025-04-28 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activity',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='activity',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('in_progress', 'En progreso'), ('completed', 'Finalizada'), ('cancelled', 'Cancelada')], default='pending', max_length=20),
        ),
    ]
