# Generated by Django 5.1.6 on 2025-04-28 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actividades', '0002_remove_activity_is_completed_activity_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['start_date']},
        ),
        migrations.RenameField(
            model_name='activity',
            old_name='date',
            new_name='start_date',
        ),
        migrations.AddField(
            model_name='activity',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
