# Generated by Django 5.1.6 on 2025-04-29 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ActivePauseAttendance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("attended", models.BooleanField(default=True)),
                (
                    "signature",
                    models.ImageField(
                        blank=True, null=True, upload_to="pausas_firmas/"
                    ),
                ),
            ],
            options={
                "ordering": ["employee_id"],
            },
        ),
        migrations.CreateModel(
            name="ActivePauseSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_deleted", models.BooleanField(default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                ("topic", models.CharField(blank=True, max_length=120)),
                ("facilitator", models.CharField(blank=True, max_length=100)),
                ("comments", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-date"],
            },
        ),
    ]
