# Generated by Django 3.2 on 2025-07-02 21:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('empleados', '0003_initial'),
        ('pausas_activas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activepausesession',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_activepausesession_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activepausesession',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_activepausesession_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activepausesession',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_activepausesession_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activepauseattendance',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_activepauseattendance_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activepauseattendance',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_activepauseattendance_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activepauseattendance',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='empleados.employee'),
        ),
        migrations.AddField(
            model_name='activepauseattendance',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='pausas_activas.activepausesession'),
        ),
        migrations.AddField(
            model_name='activepauseattendance',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_activepauseattendance_set', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='activepauseattendance',
            unique_together={('session', 'employee')},
        ),
    ]
