# Generated by Django 5.1.6 on 2025-04-24 03:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='catalogos.position')),
            ],
        ),
        migrations.CreateModel(
            name='IPVRMatrix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hazard', models.CharField(max_length=150)),
                ('risk', models.CharField(max_length=150)),
                ('control', models.TextField()),
                ('severity', models.CharField(blank=True, max_length=50)),
                ('probability', models.CharField(blank=True, max_length=50)),
                ('evaluation', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ipvr', to='ipvr.task')),
            ],
        ),
    ]
