# Generated by Django 5.1.6 on 2025-05-26 00:37

import django_multitenant.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("empresa", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="company",
            managers=[
                ("objects", django_multitenant.models.TenantManager()),
            ],
        ),
        migrations.AddField(
            model_name="company",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
