# Generated by Django 3.2 on 2025-05-26 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("empresa", "0003_alter_company_managers_company_is_active"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="company",
            options={"verbose_name": "Empresa", "verbose_name_plural": "Empresas"},
        ),
        migrations.AlterModelTable(
            name="company",
            table=None,
        ),
    ]
