# Generated by Django 5.1.6 on 2025-04-26 19:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acciones_correctivas', '0003_initial'),
        ('auditoria', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AuditExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='Abierta', max_length=50)),
                ('comments', models.TextField(blank=True)),
                ('auditor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auditoria.auditchecklist')),
            ],
        ),
        migrations.CreateModel(
            name='AuditFinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('severity', models.CharField(choices=[('Leve', 'Leve'), ('Moderado', 'Moderado'), ('Crítico', 'Crítico')], max_length=20)),
                ('status', models.CharField(choices=[('abierto', 'Abierto'), ('cerrado', 'Cerrado'), ('seguimiento', 'En seguimiento')], default='abierto', max_length=20)),
                ('closing_evidence', models.FileField(blank=True, null=True, upload_to='audit_findings_closing/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('action_item', models.ForeignKey(blank=True, help_text='Acción correctiva asociada (si aplica)', null=True, on_delete=django.db.models.deletion.SET_NULL, to='acciones_correctivas.actionitem')),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='findings', to='auditoria.auditexecution')),
            ],
        ),
        migrations.CreateModel(
            name='AuditItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('expected_result', models.CharField(blank=True, max_length=300)),
                ('evidence_required', models.BooleanField(default=False)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='auditoria.auditchecklist')),
            ],
        ),
        migrations.CreateModel(
            name='AuditResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(choices=[('cumple', 'Cumple'), ('no_cumple', 'No cumple'), ('parcial', 'Cumple parcialmente')], max_length=30)),
                ('evidence_file', models.FileField(blank=True, null=True, upload_to='audit_evidence/')),
                ('observation', models.TextField(blank=True)),
                ('execution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='auditoria.auditexecution')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auditoria.audititem')),
            ],
        ),
    ]
